/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Portal.Studio (https://sketchfab.com/Portal.Studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dyson-rings-781280bf2a3f4e8b923220106832df10
Title: DYSON RINGS
*/

import { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import { useFrame } from "@react-three/fiber";

import RingScene from "../assets/3d/dyson_rings.glb";

export function Ring({ position = [0, 0, 1], ...props }) {
  const ringRef = useRef();
  const { nodes, materials } = useGLTF(RingScene);
  const [rotationActive, setRotationActive] = useState(true);

  useFrame(() => {
    if (ringRef.current && rotationActive) {
      ringRef.current.rotation.y += 0.01;
    }
  });

  useEffect(() => {
    const timer = setTimeout(() => {
      setRotationActive(false);
    }, 8000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <a.group ref={ringRef} {...props}>
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group name="root">
            <a.group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <a.group
                name="GIRO-ANTIHORARIO_0"
                position={position}
                scale={1}
              />
              <a.group
                name="GIRO-HORARIO_1"
                position={position}
                rotation={[0, 0.016, 0]}
              />
              <a.group
                name="RING-OUT-1_2"
                position={position}
                rotation={[0, -0.016, 0]}
              >
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.MAT_METAL_1}
                />
              </a.group>
              <a.group
                name="RING-OUT-2_3"
                position={position}
                rotation={[0, 0.016, 0]}
              >
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.MAT_LIGHT_1}
                />
              </a.group>
              <a.group
                name="RING-MID-1_4"
                position={position}
                rotation={[-Math.PI / 6, 0, 0]}
                scale={[5.88, 2.2, 5.88]}
              >
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.MAT_METAL_1}
                />
              </a.group>
              <a.group
                name="RING-MID-2_5"
                position={position}
                rotation={[2.618, 1.477, -Math.PI]}
                scale={[5.88, 2.2, 5.88]}
              >
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.MAT_LIGHT_2}
                />
              </a.group>
              <a.group
                name="RING-IN-1_6"
                position={position}
                rotation={[0.059, 0.678, 0.631]}
                scale={[2.967, 1.85, 2.967]}
              >
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials.MAT_METAL_1}
                />
              </a.group>
              <a.group
                name="RING-IN-2_7"
                position={position}
                rotation={[-0.553, 1.031, 1.106]}
                scale={[2.967, 1.85, 2.967]}
              >
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials.MAT_LIGHT_3}
                />
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  );
}
export default Ring;
