/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: commonfactory (https://sketchfab.com/commonfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/night-sky-visible-spectrum-monochromatic-cfb156f03a7341b8a0a0ba0445ca742d
Title: Night Sky Visible Spectrum Monochromatic
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

import SkyScene from "../assets/3d/night_sky_visible_spectrum_monochromatic.glb";

export function Sky() {
  const sky = useGLTF(SkyScene);
  return (
    <mesh>
      <primitive object={sky.scene} />
    </mesh>
  );
}
